---
# Version of the plugin with the configuration.
config.version: "1.0.0"

# For the colors, please read the documentation on TextUtils. {greek/network/utils/TextUtils.php}
general:
  prefix: "{bold}{gold}Practice {gray}»{reset} "

# Array with available languages.
# If you want to add any other, you must also add the strings in the lang folder
languages:
  - ISOCode: "en_ENG"
    name: "English"
    icon: "https://cdn.countryflags.com/thumbs/united-states-of-america/flag-800.png"

# Credentials for the MYSQL database.
# It is extremely necessary.
#database:
#  user: "root"
#  password: "omar"
#  host: 127.0.0.1
#  database: "minecraftnetwork"
database:
  user: panel
  password: NToZzYbotvJNNeB
  host: 54.39.130.17
  database: servers

# This is an array that contains the data where the player will enter when entering the server.
# If you don't want to use this setting, put enabled: false.
spawn.options:
  enabled: true
  world.name: "world"
  x: -117
  y: 154
  z: 149
  yaw: 0
  pitch: 0
  min.void: 115
...