---
# Version of the plugin with the configuration.
config.version: "1.0.0"

# For the colors, please read the documentation on TextUtils. {greek/network/utils/TextUtils.php}
general:
  prefix: "{bold}{gold}Practice {gray}»{reset} "

# Array with available languages.
# If you want to add any other, you must also add the strings in the lang folder
languages:
  - ISOCode: "en_ENG"
    name: "English"
    icon: "https://cdn.countryflags.com/thumbs/united-states-of-america/flag-800.png"

# Credentials for the MYSQL database.
# It is extremely necessary.
#database:
#  user: "root"
#  password: "omar"
#  host: 127.0.0.1
#  database: "minecraftnetwork"
database:
  user: root
  password: omar
  host: localhost
  database: minecraft
...